# paginate: 1
# relative_permalinks: false
# syntax-highlighting:
  # css: css/code.css
# highlighter: pygments
# markdown: redcarpet
# redcarpet:
    # extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
# gems:
  # - jekyll-redirect-from

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alex Gaudio
email: adgaudio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  scientist, engineer, hacker and artist.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alexgaudio.com" # the base hostname & protocol for your site
twitter_username: adgaudio
github_username:  adgaudio

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from
