paginate: 1
relative_permalinks: false
syntax-highlighting:
  css: css/code.css
pygments: true
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
gems:
  - jekyll-redirect-from
